In [9]:
import numpy as np

#### 1

In [10]:
a = np.arange(12,24)

In [11]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2

In [12]:
la = len(a)

In [13]:
for i in range(1,7):
    if not 12%i:
        print(int(la/i),i,sep = ' ')

12 1
6 2
4 3
3 4
2 6


In [14]:
for i in range(1,7):
    if not 12%i:
        b = np.reshape(a,(int(la/i),i))
        print(b)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


#### 3

In [15]:
np.reshape(a,(1,-1))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [16]:
np.reshape(a,(2,-1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
np.reshape(a,(3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
np.reshape(a,(-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [19]:
np.reshape(a,(-1,4), order = 'F')

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

#### 4

In [20]:
cl = np.reshape(a,(12,-1))
cl

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### Можно назвать одномерным

In [21]:
cl.shape

(12, 1)

#### 5

In [22]:
x = np.random.normal(loc=0, scale=1, size=12)

In [23]:
x

array([ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769,
       -0.46572975,  0.24196227, -1.91328024, -1.72491783, -0.56228753,
       -1.01283112,  0.31424733])

In [24]:
np.reshape(x,(3,-1))

array([[ 1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112,  0.31424733]])

In [25]:
np.reshape(x,(len(x),-1))

array([[ 1.57921282],
       [ 0.76743473],
       [-0.46947439],
       [ 0.54256004],
       [-0.46341769],
       [-0.46572975],
       [ 0.24196227],
       [-1.91328024],
       [-1.72491783],
       [-0.56228753],
       [-1.01283112],
       [ 0.31424733]])

#### 6

In [26]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7

In [27]:
b = np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Массивы идентичны

#### 8

In [28]:
a = np.zeros([2,2])
a

array([[0., 0.],
       [0., 0.]])

In [29]:
b = np.ones([3,2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
vm = np.concatenate((a,b))
vm

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
vm.size

10

#### 9

In [32]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
A = np.reshape(a, (4,-1))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [35]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [36]:
B.shape

(4, 4)

In [37]:
np.linalg.det(B)

0.0

#### Размер матрицы:  кол-во строк = кол-во строк матрицы А, кол-во столбцов = кол-во столбцов матрицы At.
#### Определить матрицы B=0, следовательно матрица не обратима.

#### 10

In [38]:
np.random.seed(seed=42)

#### 11

In [39]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

#### 12

In [41]:
C = np.reshape(c, (4,4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [42]:
D = C*10 + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [43]:
np.linalg.det(D)

-28511999.999999944

In [44]:
np.linalg.matrix_rank(D)

4

In [45]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### 13

In [46]:
def f(x):
    return 1/(1+np.e**(-x))
f = np.vectorize(f)

In [47]:
D_inv = np.round(f(1000*D_inv))
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [48]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

In [49]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [50]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])