In [12]:
import numpy as np

## Вычисления с помощью Numpy

### Задание 1

In [21]:
a = np.array(([1, 2, 3, 3, 1], [6, 8, 11, 10, 7])).T

In [22]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [23]:
mean_a = a.mean(axis = 0)

In [24]:
mean_a

array([2. , 8.4])

### Задание 2

In [25]:
a_centered = np.subtract (a,mean_a)

In [26]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [28]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])

In [29]:
a_centered_sp

8.0

In [30]:
cov = a_centered_sp/(len(a)-1)

In [31]:
cov

2.0

### Задание 4

In [32]:
cov2 = np.cov(a.T)[0,1]

In [33]:
cov2

2.0